import admin from "firebase-admin";
import { readFileSync } from "fs";
import { join } from "path";

// Load configuration generated by the system setup
let firebaseConfig = {};
try {
  const configPath = join(process.cwd(), "firebase-applet-config.json");
  firebaseConfig = JSON.parse(readFileSync(configPath, "utf8"));
  console.log("Loaded Firebase Applet Config successfully.", firebaseConfig.projectId);
} catch (err) {
  console.warn("Could not find firebase-applet-config.json. Using env variables fallback.");
}

const projectId = process.env.FIREBASE_PROJECT_ID || firebaseConfig.projectId || "aerobic-limiter-jtsmh";
const databaseId = firebaseConfig.firestoreDatabaseId;

if (admin.apps.length === 0) {
  admin.initializeApp({
    projectId: projectId,
  });
}

// Connect to the custom Firestore database if auto-provisioned
export const db = databaseId
  ? new admin.firestore.Firestore({ projectId, databaseId })
  : admin.firestore();

console.log(`Firestore initialized for project ${projectId} (Database: ${databaseId || "default"})`);

export default admin;
